import {readdirSync,readFileSync,writeFileSync} from 'node:fs'
import {join,relative,extname} from 'node:path'
const root=new URL('../public/',import.meta.url).pathname
const entries=[]
function visit(dir){for(const item of readdirSync(dir,{withFileTypes:true})){
 const path=join(dir,item.name)
 if(item.isDirectory()){visit(path);continue}
 const type={'.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'}[extname(path)]
 if(!type)throw new Error('Unsupported asset '+path)
 entries.push(JSON.stringify('/'+relative(root,path))+': {type:'+JSON.stringify(type)+',body:Buffer.from('+JSON.stringify(readFileSync(path).toString('base64'))+",'base64')}")
}}
visit(root)
writeFileSync(new URL('../src/server/assets.ts',import.meta.url),'// Generated by scripts/build-assets.mjs from public/.\nexport const assets: Record<string,{type:string;body:Buffer}> = {\n'+entries.join(',\n')+'\n}\n')
